export const AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';
export const AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED';
export const DUPLICATE_USER = 'DUPLICATE_USER';
export const INVALID_USER_SCHEMA = 'INVALID_USER_SCHEMA';
export const INSUFFICIENT_PRIVILEGE = 'INSUFFICIENT_PRIVILEGE';
